name: Build FanChmWrt AX3000T

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache compile resource
        uses: actions/cache@v4
        with:
          path: |
            dl
            build_dir
          key: ${{ runner.os }}-fanchmwrt-ax3000t-v2

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libncurses-dev \
            zlib1g-dev \
            gawk \
            git \
            gettext \
            unzip \
            file \
            rsync \
            python3

      - name: Update feeds source
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure device & keep only app-center
        run: |
          echo "CONFIG_TARGET_mediatek=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic_DEVICE_xiaomi_mi-router-ax3000t-ubootmod=y" >> .config

          # 无线基础组件
          echo "CONFIG_PACKAGE_wpad-basic-mbedtls=y" >> .config
          echo "CONFIG_PACKAGE_iwinfo=y" >> .config

          # HTTPS 证书
          echo "CONFIG_PACKAGE_ca-bundle=y" >> .config
          echo "CONFIG_PACKAGE_ca-certificates=y" >> .config

          # FanChmWrt 官方应用中心
          echo "CONFIG_PACKAGE_luci-app-fwx-app-center=y" >> .config

          make defconfig

      - name: Build firmware
        run: |
          set -e
          make -j2 V=s

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: AX3000T-FanChmWrt-OnlyAppCenter
          path: bin/targets/**
