      - name: Configure device & keep only app-center
        run: |
          echo "CONFIG_TARGET_mediatek=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic_DEVICE_xiaomi_mi-router-ax3000t-ubootmod=y" >> .config

          # 无线基础必备组件
          echo "CONFIG_PACKAGE_wpad-basic-mbedtls=y" >> .config
          echo "CONFIG_PACKAGE_iwinfo=y" >> .config
          # 证书依赖（应用商店联网下载安装包必需）
          echo "CONFIG_PACKAGE_ca-bundle=y" >> .config
          echo "CONFIG_PACKAGE_ca-certificates=y" >> .config
          # 仅保留FanChmWrt官方应用商店
          echo "CONFIG_PACKAGE_luci-app-fwx-app-center=y" >> .config

          # 关闭elfutils调试工具，规避宏重定义编译故障，路由器固件不需要它
          echo "CONFIG_PACKAGE_elfutils=n" >> .config

          make defconfig
